### PR TITLE
Warns on error-prone and unnecessary negations

### LINKED ISSUE #43: Question: is there interest in adding warnings about questionable expressions?
Hi, I've just fixed a bug in a game's Lua code, which looked like this:
```lua
if not mem.state==2 or not cargo_space then  -- expecting (not (mem.state == 2)) precedence
```
This is a rather elementary mistake, but after looking at other languages I think there could be a useful warning in here: Python reverses the precedence between "not" and comparisons. For C, which doesn't, gcc and Clang offer this warning option: "-Wlogical-not-parentheses: Warn about logical not used on the left hand side operand of a comparison".

As far as I can tell, Luacheck can parse expressions but doesn't have any warning category for valid-but-potentially-suspicious ones. Is that a use case which sounds interesting to support?

Thanks for your thoughts.

### PR DESCRIPTION
**Pull request by arichard4**
Closes #43

### CODE REVIEW

**Comment by arichard4** [comment]
One false positive here: sometimes metatables override the various boolean operators, and end up implementing them in terms of each other.

**Comment by alerque** [comment]
Having *not* actually run this bot looking at the code, then looking at use cases from my own code, wouldn't this be a false positive for a situation like this:

```lua
if not (t and #t >= 1) then ... end
```

?

**Comment by arichard4** [comment]
I'll update the docs to talk specifically about 'relational operators' rather than 'binary boolean operators'; that's the correct term, and it's clearer.

**Comment by arichard4** [comment]
Oh, one more false-positive case: if one side is NaN, the proposed replacement would fail. (Because for any concrete number, NaN isn't greater than, equal to, *or* less than that number.)

**Comment by arichard4** [comment]
@alerque For context- I have a local test suite of 13 large open source projects that use luacheck already; the only false positive, so far as I can tell, was luarocks, line 63 here: https://github.com/luarocks/luarocks/blob/master/src/luarocks/core/vers.lua

It seems like no projects actually cared about the NaN case, but in theory that could matter too.

**Review by alerque — APPROVED** [review]
I think my only remaining objection is the false positives this generates in my own projects, but the cases are all metatable related and convoluted that the reason why they use an unconventional order really should be annotated anyway, so having to adding a lint suppression seems fair enough.

**Comment by alerque** [comment]
@arichard4 It might be a good idea to submit a fix with a lint suppressor for that Luarocks metatable trickery (or flip it and add a `:__ge` method to compensate) so that the fix can land before this lint issue pops up.

**Comment by alerque** [comment]
Any idea what's up with the Luajit test segfault?

**Comment by arichard4** [comment]
Both the luajit test jobs seems to frequently suffer segfaults. Some things I've noticed:

(1) They're both building against Luajit 2.1-beta3, which is *way* out of date (from 2017); plausibly they should try to build against a more recent commit instead.
(2) As of 2017, there were a bunch of issues reported in busted/luassert involving busted reloading requires, and the previous required modules getting GC'd, causing luajit-specific segfaults: e.g. https://github.com/Olivine-Labs/busted/issues/496

**Pull request merged**
