### PR TITLE
Use built-in bitwise operations with lua 5.4 (#112)

### LINKED ISSUE #112: luacheck with lua5.4 does not use built-in bitwise operations
See [src/luacheck/vendor/sha1/init.lua choose_ops function](https://github.com/lunarmodules/luacheck/blob/cc089e3f65acdd1ef8716cc73a3eca24a6b845e4/src/luacheck/vendor/sha1/init.lua#L41): there is the hard code with 5.3, not for versions above.

### PR DESCRIPTION
**Pull request by rautyrauty**
Closes #112

### CODE REVIEW

**Comment by rautyrauty** [comment]
ping

**Comment by rautyrauty** [comment]
@alerque review please

**Comment by rautyrauty** [comment]
@alerque review please. The fix is trivial!

**Comment by rautyrauty** [comment]
@alerque ping

**Comment by alerque** [comment]
Please stop being so rude. Contributions are welcome, but pestering FOSS maintainers is not. This isn't my day job and –trivial or not– handling PRs takes time.

**Pull request merged**
